### ISSUE TITLE
Map Section: Station Interactions in Map

### ISSUE THREAD

**Issue by vnbl** [vnbl/respira-webapp#27]
## Note: Issues are only closed after merging to dev

When clicking on a station marker on the map, the side panel should display the corresponding monitoring and forecasting data for the selected station.
# Tasks (only mark as completed after creating a PR)

Look & Layout
- [x] Ensure the side panel follows the design guidelines and matches the desired layout.
    - [x] slider on monitoring data
    - [x] logarithmic scale for 6h and 12 forecasts. Correct color for graph bars according to AQI standard in design

Interactions
- [x] On marker click: Fetch and display relevant data (monitoring, 6h and 12h forecasting) for the specific station in the side panel.
- [x] Ensure only one station's data is visible at a time. Clicking a new marker should replace sideview the content.
- [x] Working 'Recomendaciones por nivel' button, points to 'Recomendaciones por nivel' -> #25 

Acceptance Criteria

- [x] Clicking a station marker displays the correct data in the side panel.
- [x] UI layout looks consistent and matches the design.
- [x] All interactions are responsive and bug-free.

![image](https://github.com/user-attachments/assets/a318d51e-3d66-42ab-8f10-1e1311b91fa5)
